# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/WorkSpace/project/FPGA/SC130_3Channel/SC130_3Channel/SC130_3Channel.srcs/sources_1/ip/normalize_bram/normalize_bram.xci
# IP: The module: 'normalize_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/SC130_3Channel/SC130_3Channel/SC130_3Channel.srcs/sources_1/ip/normalize_bram/normalize_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'normalize_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/WorkSpace/project/FPGA/SC130_3Channel/SC130_3Channel/SC130_3Channel.srcs/sources_1/ip/normalize_bram/normalize_bram.xci
# IP: The module: 'normalize_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/SC130_3Channel/SC130_3Channel/SC130_3Channel.srcs/sources_1/ip/normalize_bram/normalize_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'normalize_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
