# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Program/FPGA/WORKING/camera30/SC130_3Channel/prj_sc130.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xci
# IP: The module: 'fifo_maxtrix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program/FPGA/WORKING/camera30/SC130_3Channel/prj_sc130.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Program/FPGA/WORKING/camera30/SC130_3Channel/prj_sc130.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Program/FPGA/WORKING/camera30/SC130_3Channel/prj_sc130.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xci
# IP: The module: 'fifo_maxtrix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program/FPGA/WORKING/camera30/SC130_3Channel/prj_sc130.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Program/FPGA/WORKING/camera30/SC130_3Channel/prj_sc130.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
